### ISSUE TITLE
MasterSlider Skin images should be installed with theme

### ISSUE THREAD

**Issue by Gorcenski** [getgrav/grav-theme-soraarticle#6]
In https://github.com/getgrav/grav-theme-soraarticle/blob/bb20932cd168b43dec01fbf3e5ea45069ced1516/css/style.css#L3402, the code reads:

``` CSS
.ms-skin-default .ms-video-btn{
    width: 50px;
    height: 51px;
    background: url(skins/light-skin-1.png) no-repeat -14px -150px;
    top: 50%;
    left: 50%;
    margin: -25px 0 0 -25px;
}
```

However, after installation of the theme, there is no `css/skins` folder, so a 404 error is logged for the missing background images named `css/skins/light-skin-1.png` and similar for the dark themes.
